### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by Olteon** [RandomShaper/godot-paris-apr-17#1]
Hola Pedro,

Soy Fernando, nos conocimos en el meet the nodes de Paris. No se como, cambiando de movil, perdi tu direccion de correo. ¿Como me puedo poner en contacto contigo?

Un saludo

**Comment by RandomShaper** [comment]
¡Muy buenas!

Te contesto al correo.

**Comment by RandomShaper** [comment]
Menuda tontería acabo de decir. :P

Mi correo es pedrojrulez@gmail.com.
